### ISSUE TITLE
Error during pom.xml analysis

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#105]
pom.xml that was sent to analyze:

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.redhat.bayessian.test</groupId>
  <artifactId>test-app-junit-dependency</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
    </dependency>
  </dependencies>
</project>
```

Error log:

```
{"storage_task_name": "recommendation_v2", "task_id": "cebb1825-8f51-47fb-9fd0-75e621dc060d", "storage_name": "BayesianPostgres", "error_type": "<class 'KeyError'>", "flow_name": "stackApiGraphV2Flow", "node_args": {"ecosystem": null, "data": {"request": [{"ecosystem": "maven", "filename": "pom.xml", "content": "<project>\n <modelVersion>4.0.0</modelVersion>\n <groupId>com.redhat.bayessian.test</groupId>\n <artifactId>test-app-junit-dependency</artifactId>\n <version>1.0</version>\n <dependencies>\n <dependency>\n <groupId>junit</groupId>\n <artifactId>junit</artifactId>\n <version>3.8.1</version>\n </dependency>\n </dependencies>\n</project>\n"}], "user_profile": {"nbf": 0, "preferred_username": "bayesian", "sub": "0608c567-62ad-4d04-bf4c-139f249fba5c", "iat": 1501495892, "email": "bayesian-api@openshift.io", "azp": "fabric8-online-platform", "allowed-origins": ["*"], "aud": "fabric8-online-platform", "jti": "9ab0b02e-241a-474f-90db-c98d4e6dd638", "company": "Red Hat", "typ": "Bearer", "realm_access": {"roles": ["offline_access", "uma_authorization"]}, "session_state": "02955b8d-c8fd-4489-bf9b-81e6d54e11ff", "acr": "1", "auth_time": 0, "iss": "https://sso.prod-preview.openshift.io/auth/realms/fabric8", "exp": 1533031892, "resource_access": {"account": {"roles": ["manage-account", "manage-account-links", "view-profile"]}, "broker": {"roles": ["read-token"]}}}, "user_email": "bayesian-api@openshift.io", "api_name": "stack_analyses"}, "external_request_id": "7f69df4112724f5382364f0aabbc50b6", "manifest": [{"ecosystem": "maven", "filename": "pom.xml", "content": "<project>\n <modelVersion>4.0.0</modelVersion>\n <groupId>com.redhat.bayessian.test</groupId>\n <artifactId>test-app-junit-dependency</artifactId>\n <version>1.0</version>\n <dependencies>\n <dependency>\n <groupId>junit</groupId>\n <artifactId>junit</artifactId>\n <version>3.8.1</version>\n </dependency>\n </dependencies>\n</project>\n"}]}, "task_name": "recommendation_v2", "error_traceback": " File \"
/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/recommender.py\", line 620, in execute\n    alt_packages = create_package_dict(alt_packages_graph, final_dict)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/graphutils.py\", line 272, in create_package_dict\n    \"average_cyclomatic_complexity\": epv['ver']['cm_avg_cyclomatic_complexity'][0],\n", "error_value": "'cm_avg_cyclomatic_complexity'", "event": "STORAGE_STORE_ERROR", "record_id": null}
2017-08-01 15:45:50,504 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[cebb1825-8f51-47fb-9fd0-75e621dc060d] raised unexpected: KeyError('cm_avg_cyclomatic_complexity',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
    result = task.run(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run
    result = self.execute(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/recommender.py", line 620, in execute
    alt_packages = create_package_dict(alt_packages_graph, final_dict)
  File "/usr/lib/python3.4/site-packages/f8a_worker/graphutils.py", line 272, in create_package_dict
    "average_cyclomatic_complexity": epv['ver']['cm_avg_cyclomatic_complexity'][0],
KeyError: 'cm_avg_cyclomatic_complexity'
```

**Comment by tisnik** [comment]
It seems to be already fixed by https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/195
