### ISSUE TITLE
Internal Server Error - when using component analyses API

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-server#154]
I have encountered error when using component analyses API `GET /api/v1/component-analyses/go/go/1.0`

```
172.17.0.1 - - [19/Sep/2017:07:32:07 +0000] "GET / HTTP/1.1" 302 221 - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
172.17.0.1 - - [19/Sep/2017:07:32:07 +0000] "GET /api/v1 HTTP/1.1" 200 487 - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
172.17.0.1 - - [19/Sep/2017:07:32:07 +0000] "GET /favicon.ico HTTP/1.1" 404 233 http://localhost:32000/api/v1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"

mod_wsgi (pid=9): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:5000:0/htdocs/api'.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/mod_wsgi/server/__init__.py", line 1484, in handle_request
    return self.application(environ, start_response)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/bayesian/api_v1.py", line 206, in dispatch_request
    response = super().dispatch_request(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/bayesian/auth.py", line 53, in wrapper
    return view(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/bayesian/api_v1.py", line 272, in get
    server_create_analysis(ecosystem, package, version, user_profile=decoded, api_flow=False, force=False, force_graph_sync=True)
  File "/usr/lib/python3.4/site-packages/bayesian/utils.py", line 63, in server_create_analysis
    server_create_component_bookkeeping(ecosystem, component, version, user_profile)
  File "/usr/lib/python3.4/site-packages/bayesian/utils.py", line 44, in server_create_component_bookkeeping
    'user_email': user_profile.get('email','bayesian@redhat.com'),
AttributeError: 'NoneType' object has no attribute 'get'

172.17.0.1 - - [19/Sep/2017:07:32:34 +0000] "GET /api/v1/component-analyses/go/go/1.0 HTTP/1.1" 500 531 - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.
```

**Comment by fridex** [comment]
Related: https://github.com/fabric8-analytics/fabric8-analytics-server/pull/89

**Comment by samuzzal-choudhury** [comment]
@tuxdna did the fix in https://github.com/fabric8-analytics/fabric8-analytics-server/pull/89 fix this issue?

**Comment by tuxdna** [comment]
@samuzzal-choudhury Yes that PR does fix this.

**Comment by tuxdna** [comment]
Closing via: https://github.com/fabric8-analytics/fabric8-analytics-server/pull/89
