### ISSUE TITLE
KeyError: 'SENTRY_DSN'

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-server#272]
With latest images, and doing ./docker-compose.sh up I see this error:

```
coreapi-server          | [Tue Feb 27 07:44:25.520638 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054] Traceback (most recent call last):
coreapi-server          | [Tue Feb 27 07:44:25.520728 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/tmp/mod_wsgi-localhost:5000:0/handler.wsgi", line 94, in <module>
coreapi-server          | [Tue Feb 27 07:44:25.520746 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     recorder_directory=recorder_directory)
coreapi-server          | [Tue Feb 27 07:44:25.520794 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib64/python3.4/site-packages/mod_wsgi/server/__init__.py", line 1374, in __init__
coreapi-server          | [Tue Feb 27 07:44:25.520807 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     __import__(entry_point)
coreapi-server          | [Tue Feb 27 07:44:25.520846 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/bayesian/__init__.py", line 101, in <module>
coreapi-server          | [Tue Feb 27 07:44:25.520858 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     init_selinon()
coreapi-server          | [Tue Feb 27 07:44:25.520895 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/f8a_worker/setup_celery.py", line 49, in init_selinon
coreapi-server          | [Tue Feb 27 07:44:25.520906 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     Config.set_config_yaml(nodes_config, flows_config)
coreapi-server          | [Tue Feb 27 07:44:25.520948 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/selinon/config.py", line 140, in set_config_yaml
coreapi-server          | [Tue Feb 27 07:44:25.520960 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     system = System.from_files(nodes_definition_file, flow_definition_files)
coreapi-server          | [Tue Feb 27 07:44:25.520997 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/selinon/system.py", line 1159, in from_files
coreapi-server          | [Tue Feb 27 07:44:25.521003 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     cls._setup_nodes(system, nodes_definition, nodes_definition_file)
coreapi-server          | [Tue Feb 27 07:44:25.521026 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/selinon/system.py", line 1074, in _setup_nodes
coreapi-server          | [Tue Feb 27 07:44:25.521031 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     GlobalConfig.from_dict(system, nodes_definition['global'])
coreapi-server          | [Tue Feb 27 07:44:25.521054 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/selinon/global_config.py", line 198, in from_dict
coreapi-server          | [Tue Feb 27 07:44:25.521066 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     cls._parse_trace(system, dict_.pop('trace'))
coreapi-server          | [Tue Feb 27 07:44:25.521097 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/selinon/global_config.py", line 182, in _parse_trace
coreapi-server          | [Tue Feb 27 07:44:25.521102 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     cls._parse_trace_sentry(entry['sentry'])
coreapi-server          | [Tue Feb 27 07:44:25.521126 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]   File "/usr/lib/python3.4/site-packages/selinon/global_config.py", line 138, in _parse_trace_sentry
coreapi-server          | [Tue Feb 27 07:44:25.521131 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054]     dsn = dsn.format(**os.environ)
coreapi-server          | [Tue Feb 27 07:44:25.521152 2018] [wsgi:error] [pid 94:tid 140675480364800] [remote 172.17.0.1:51054] KeyError: 'SENTRY_DSN'
```

**Comment by msrb** [comment]
Should be fixed, thanks for the PR! :)
