### ISSUE TITLE
ImportError: cannot import name 'tempdir'

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-server#273]
With latest images, and doing ./docker-compose.sh up I see this error:

```
oreapi-server          | [Tue Feb 27 07:49:01.284106 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042] mod_wsgi (pid=95): Target WSGI script '/tmp/mod_wsgi-localhost:5000:0/handler.wsgi' cannot be loaded as Python module.
coreapi-server          | [Tue Feb 27 07:49:01.284162 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042] mod_wsgi (pid=95): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:5000:0/handler.wsgi'.
coreapi-server          | [Tue Feb 27 07:49:01.284214 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042] Traceback (most recent call last):
coreapi-server          | [Tue Feb 27 07:49:01.284312 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]   File "/tmp/mod_wsgi-localhost:5000:0/handler.wsgi", line 94, in <module>
coreapi-server          | [Tue Feb 27 07:49:01.284331 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]     recorder_directory=recorder_directory)
coreapi-server          | [Tue Feb 27 07:49:01.284387 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]   File "/usr/lib64/python3.4/site-packages/mod_wsgi/server/__init__.py", line 1374, in __init__
coreapi-server          | [Tue Feb 27 07:49:01.284403 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]     __import__(entry_point)
coreapi-server          | [Tue Feb 27 07:49:01.284453 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]   File "/usr/lib/python3.4/site-packages/bayesian/__init__.py", line 103, in <module>
coreapi-server          | [Tue Feb 27 07:49:01.284468 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]     app = create_app()
coreapi-server          | [Tue Feb 27 07:49:01.284515 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]   File "/usr/lib/python3.4/site-packages/bayesian/__init__.py", line 39, in create_app
coreapi-server          | [Tue Feb 27 07:49:01.284531 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]     from .api_v1 import api_v1
coreapi-server          | [Tue Feb 27 07:49:01.284574 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]   File "/usr/lib/python3.4/site-packages/bayesian/api_v1.py", line 32, in <module>
coreapi-server          | [Tue Feb 27 07:49:01.284588 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]     from .dependency_finder import DependencyFinder
coreapi-server          | [Tue Feb 27 07:49:01.284631 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]   File "/usr/lib/python3.4/site-packages/bayesian/dependency_finder.py", line 11, in <module>
coreapi-server          | [Tue Feb 27 07:49:01.284647 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042]     from f8a_worker.utils import tempdir
coreapi-server          | [Tue Feb 27 07:49:01.284684 2018] [wsgi:error] [pid 95:tid 140057391953664] [remote 172.17.0.1:54042] ImportError: cannot import name 'tempdir'

```

**Comment by jpopelka** [comment]
Ah, sorry for that and thanks for the fix.
