### ISSUE TITLE
HTTP code 500 is returned when wrong ecosystem is used in component analysis call

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#489]
Component analysis accepts input data in following format:

```
api/v1/component-analyses/{ecosystem}/{package}/{version}
```

When wrong ecosystem is provided, the HTTP code 500 is returned, but some other code from 4xx group is expected.

Excerpt from logs:

```
[Wed Apr 24 07:58:25.187680 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] [2019-04-24 07:58:25,187] ERROR in app: Exception on /api/v1/component-analyses/mvn/jquery/1.9.1 [GET]
[Wed Apr 24 07:58:25.187705 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] Traceback (most recent call last):
[Wed Apr 24 07:58:25.187709 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
[Wed Apr 24 07:58:25.187715 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     rv = self.dispatch_request()
[Wed Apr 24 07:58:25.187718 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
[Wed Apr 24 07:58:25.187724 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Apr 24 07:58:25.187726 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
[Wed Apr 24 07:58:25.187731 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     resp = resource(*args, **kwargs)
[Wed Apr 24 07:58:25.187734 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask/views.py", line 84, in view
[Wed Apr 24 07:58:25.187749 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return self.dispatch_request(*args, **kwargs)
[Wed Apr 24 07:58:25.187751 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
[Wed Apr 24 07:58:25.187753 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     resp = meth(*args, **kwargs)
[Wed Apr 24 07:58:25.187761 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/fabric8a_auth/auth.py", line 125, in wrapper
[Wed Apr 24 07:58:25.187763 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return view(*args, **kwargs)
[Wed Apr 24 07:58:25.187765 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/bayesian/api_v1.py", line 245, in get
[Wed Apr 24 07:58:25.187767 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     package = case_sensitivity_transform(ecosystem, package)
[Wed Apr 24 07:58:25.187769 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/f8a_worker/utils.py", line 499, in case_sensitivity_transform
[Wed Apr 24 07:58:25.187772 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     ecosystem).is_backed_by(EcosystemBackend.pypi):
[Wed Apr 24 07:58:25.187779 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/f8a_worker/models.py", line 123, in by_name
[Wed Apr 24 07:58:25.187782 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return cls._by_attrs(session, name=name)
[Wed Apr 24 07:58:25.187784 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/f8a_worker/models.py", line 51, in _by_attrs
[Wed Apr 24 07:58:25.187787 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return session.query(cls).filter_by(**attrs).one()
[Wed Apr 24 07:58:25.187795 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2960, in one
[Wed Apr 24 07:58:25.187797 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     raise orm_exc.NoResultFound("No row was found for one()")
[Wed Apr 24 07:58:25.187802 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] sqlalchemy.orm.exc.NoResultFound: No row was found for one()
[Wed Apr 24 07:58:25.187821 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] 
[Wed Apr 24 07:58:25.187869 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] Exception on /api/v1/component-analyses/mvn/jquery/1.9.1 [GET]
[Wed Apr 24 07:58:25.187878 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] Traceback (most recent call last):
[Wed Apr 24 07:58:25.187881 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
[Wed Apr 24 07:58:25.187886 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     rv = self.dispatch_request()
[Wed Apr 24 07:58:25.187888 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
[Wed Apr 24 07:58:25.187890 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Apr 24 07:58:25.187892 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
[Wed Apr 24 07:58:25.187894 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     resp = resource(*args, **kwargs)
[Wed Apr 24 07:58:25.187896 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask/views.py", line 84, in view
[Wed Apr 24 07:58:25.187899 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return self.dispatch_request(*args, **kwargs)
[Wed Apr 24 07:58:25.187901 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
[Wed Apr 24 07:58:25.187905 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     resp = meth(*args, **kwargs)
[Wed Apr 24 07:58:25.187907 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/fabric8a_auth/auth.py", line 125, in wrapper
[Wed Apr 24 07:58:25.187910 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return view(*args, **kwargs)
[Wed Apr 24 07:58:25.187915 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/bayesian/api_v1.py", line 245, in get
[Wed Apr 24 07:58:25.187917 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     package = case_sensitivity_transform(ecosystem, package)
[Wed Apr 24 07:58:25.187919 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/f8a_worker/utils.py", line 499, in case_sensitivity_transform
[Wed Apr 24 07:58:25.187925 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     ecosystem).is_backed_by(EcosystemBackend.pypi):
[Wed Apr 24 07:58:25.187927 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/f8a_worker/models.py", line 123, in by_name
[Wed Apr 24 07:58:25.187929 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return cls._by_attrs(session, name=name)
[Wed Apr 24 07:58:25.187934 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib/python3.6/site-packages/f8a_worker/models.py", line 51, in _by_attrs
[Wed Apr 24 07:58:25.187936 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     return session.query(cls).filter_by(**attrs).one()
[Wed Apr 24 07:58:25.187938 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2960, in one
[Wed Apr 24 07:58:25.187944 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120]     raise orm_exc.NoResultFound("No row was found for one()")
[Wed Apr 24 07:58:25.187947 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] sqlalchemy.orm.exc.NoResultFound: No row was found for one()
[Wed Apr 24 07:58:25.187951 2019] [wsgi:error] [pid 120:tid 140472534165248] [remote 10.130.4.1:53120] 
10.130.4.1 - - [24/Apr/2019:07:58:25 +0000] "GET /api/v1/component-analyses/mvn/jquery/1.9.1 HTTP/1.1" 500 43 - "python-requests/2.13.0"
```

**Comment by rootAvish** [comment]
Interestingly enough, there does exist a maven jquery 1.9.1: https://mvnrepository.com/artifact/org.webjars/jquery/1.9.1. Should there be an error at all here?

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-server/pull/494#pullrequestreview-232918069
