### ISSUE TITLE
Stack analyses v2 failure for pom.xml, probably because ecosystem is not set properly?

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#98]
Stack analyses v2 fails for the current pom.xml file:

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.redhat.bayessian.test</groupId>
  <artifactId>test-app-junit-dependency</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
    </dependency>
  </dependencies>
</project>
```

After the pom.xml is sent to the analysis, the following log message can be seen:

```
worker-api_1            | cher_id": "56e775c3-7e8f-4df9-92da-ea96820f7c8b", "task_name": "GraphAggregatorTask", "flow_name": "stackApiGraphV2Flow", "parent": {}, "task_id": "12cf991c-26f5-482f-b5cc-739a171ee124", "node_args": {"manifest": [{"content": "<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.redhat.bayessian.test</groupId>\n  <artifactId>test-app-junit-dependency</artifactId>\n  <version>1.0</version>\n  <dependencies>\n    <dependency>\n      <groupId>junit</groupId>\n      <artifactId>junit</artifactId>\n      <version>3.8.1</version>\n    </dependency>\n  </dependencies>\n</project>\n", "ecosystem": "maven", "filename": "pom.xml"}], "data": {"user_email": "bayesian@redhat.com", "api_name": "stack_analyses", "user_profile": {"iat": 1500567890, "exp": 1508343890, "sub": "testuser"}, "request": [{"content": "<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.redhat.bayessian.test</groupId>\n  <artifactId>test-app-junit-dependency</artifactId>\n  <version>1.0</version>\n  <dependencies>\n    <dependency>\n      <groupId>junit</groupId>\n      <artifactId>junit</artifactId>\n      <version>3.8.1</version>\n    </dependency>\n  </dependencies>\n</project>\n", "ecosystem": "maven", "filename": "pom.xml"}]}, "ecosystem": null, "external_request_id": "0ba28a835040495ab5d092ed13cca7ea"}, "event": "TASK_START", "queue": "ptisnovs_api_GraphAggregatorTask_v0"}
```

After a while:

```
worker-api_1            | {"dispatcher_id": "56e775c3-7e8f-4df9-92da-ea96820f7c8b", "selective": false, "flow_name": "stackApiGraphV2Flow", "node_name": "recommendation_v2", "node_id": "8207b164-afce-472a-b69c-6771b8d76854", "what": "Traceback (most recent call last):\n  File \"/usr/lib/python3.4/site-packages/celery/app/trace.py\", line 367, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/usr/lib/python3.4/site-packages/celery/app/trace.py\", line 622, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 170, in run\n    raise self.retry(max_retries=0, exc=exc)\n  File \"/usr/lib/python3.4/site-packages/celery/app/task.py\", line 668, in retry\n    raise_with_context(exc)\n  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 38, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/recommender.py\", line 571, in execute\n    for pgm_result in pgm_response:\nTypeError: 'NoneType' object is not iterable\n", "event": "NODE_FAILURE"}
worker-api_1            | ive": false, "retry": 4, "node_args": {"manifest": [{"content": "<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.redhat.bayessian.test</groupId>\n  <artifactId>test-app-junit-dependency</artifactId>\n  <version>1.0</version>\n  <dependencies>\n    <dependency>\n      <groupId>junit</groupId>\n      <artifactId>junit</artifactId>\n      <version>3.8.1</version>\n    </dependency>\n  </dependencies>\n</project>\n", "ecosystem": "maven", "filename": "pom.xml"}], "data": {"api_name": "stack_analyses", "user_email": "bayesian@redhat.com", "user_profile": {"iat": 1500567890, "exp": 1508343890, "sub": "testuser"}, "request": [{"content": "<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.redhat.bayessian.test</groupId>\n  <artifactId>test-app-junit-dependency</artifactId>\n  <version>1.0</version>\n  <dependencies>\n    <dependency>\n      <groupId>junit</groupId>\n      <artifactId>junit</artifactId>\n      <version>3.8.1</version>\n    </dependency>\n  </dependencies>\n</project>\n", "ecosystem": "maven", "filename": "pom.xml"}]}, "ecosystem": null, "external_request_id": "0ba28a835040495ab5d092ed13cca7ea"}, "event": "FLOW_FAILURE", "queue": "ptisnovs_api_stackApiGraphFlow_v0", "dispatcher_id": "56e775c3-7e8f-4df9-92da-ea96820f7c8b", "flow_name": "stackApiGraphV2Flow", "parent": null, "will_retry": false, "state": {"finished_nodes": {"GraphAggregatorTask": ["12cf991c-26f5-482f-b5cc-739a171ee124"], "ManifestKeeperTask": ["b8897e79-8bcc-4d90-b031-a685173c46fd"], "BookkeeperTask": ["1a71f258-e88d-4e5a-96c0-3b3f1050fef0"], "stack_aggregator_v2": ["757206f6-2f09-4260-b929-3e717a38e896"]}, "failed_nodes": {"recommendation_v2": ["8207b164-afce-472a-b69c-6771b8d76854"]}}}
coreapi-pgbouncer       | 2017-07-28 13:58:12.978 14 LOG C-0x147a6f0: coreapi/coreapi@172.17.0.14:35104 login attempt: db=coreapi user=coreapi tls=no
coreapi-pgbouncer       | 2017-07-28 13:58:12.987 14 LOG C-0x147a6f0: coreapi/coreapi@172.17.0.14:35104 closing because: client close request (age=0)
worker-api_1            | 28 13:58:12,987 [ERROR] celery.app.trace: Task selinon.Dispatcher[56e775c3-7e8f-4df9-92da-ea96820f7c8b] raised unexpected: FlowError('{"finished_nodes": {"GraphAggregatorTask": ["12cf991c-26f5-482f-b5cc-739a171ee124"], "ManifestKeeperTask": ["b8897e79-8bcc-4d90-b031-a685173c46fd"], "BookkeeperTask": ["1a71f258-e88d-4e5a-96c0-3b3f1050fef0"], "stack_aggregator_v2": ["757206f6-2f09-4260-b929-3e717a38e896"]}, "failed_nodes": {"recommendation_v2": ["8207b164-afce-472a-b69c-6771b8d76854"]}}',)
worker-api_1            | Traceback (most recent call last):
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
worker-api_1            |     R = retval = fun(*args, **kwargs)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
worker-api_1            |     return self.run(*args, **kwargs)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/selinon/dispatcher.py", line 103, in run
worker-api_1            |     raise self.retry(max_retries=0, exc=flow_error)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
worker-api_1            |     raise_with_context(exc)
worker-api_1            |   File "/usr/lib/python3.4/site-packages/selinon/dispatcher.py", line 83, in run
worker-api_1            |     retry = system_state.update()
worker-api_1            |   File "/usr/lib/python3.4/site-packages/selinon/systemState.py", line 760, in update
worker-api_1            |     started, reused, fallback_started = self._continue_and_update_retry([])
worker-api_1            |   File "/usr/lib/python3.4/site-packages/selinon/systemState.py", line 745, in _continue_and_update_retry
worker-api_1            |     raise FlowError(json.dumps(state_info))
worker-api_1            | selinon.errors.FlowError: {"finished_nodes": {"GraphAggregatorTask": ["12cf991c-26f5-482f-b5cc-739a171ee124"], "ManifestKeeperTask": ["b8897e79-8bcc-4d90-b031-a685173c46fd"], "BookkeeperTask": ["1a71f258-e88d-4e5a-96c0-3b3f1050fef0"], "stack_aggregator_v2": ["757206f6-2f09-4260-b929-3e717a38e896"]}, "failed_nodes": {"recommendation_v2": ["8207b164-afce-472a-b69c-6771b8d76854"]}}
```

**Comment by samuzzal-choudhury** [comment]
@tisnik this is working fine now for that pom.xml:
https://recommender.api.openshift.io/api/v1/stack-analyses/a8bf8c1eb5c84e0d9adaa73a40fb6b7b

Hence, closing. Please reopen if you think otherwise.
